use_frameworks!

target 'AKAnalysisManager_Example' do
  pod 'AKAnalysisManager', :path => '../'
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
    end

  target 'AKAnalysisManager_Tests' do
    inherit! :search_paths

    
  end
end
